import React from 'react';
import Navbar from "./Navbar";
import Footer from "./Footer";
import Head from 'next/head';

const Layout = ({children}: {children: React.ReactNode}) => {
    return ( 
        <div>
            <Head>
                <title>Find Home</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
                <link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/nprogress/0.2.0/nprogress.min.css' integrity='sha512-42kB9yDlYiCEfx2xVwq0q7hT4uf26FUgSIZBK8uiaEnTdShXjwr8Ip1V4xGJMg3mHkUt9nNuTDxunHF0/EgxLQ==' crossOrigin='anonymous' referrerPolicy='no-referrer' />
            </Head>
            <Navbar />  
            <main className="container mx-auto max-w-7xl px-4 py-4">
                {children}
                <Footer />
            </main>
        </div>
    );
}

export default Layout;