import React from 'react';
import Navbar from "./Navbar";
import Head from 'next/head';
const Layout = ({children}: {children: React.ReactNode}) => {
    return ( 
        <div>
        <Head>
            <title>Find Home</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
            <Navbar />  
            <main className="container mx-auto max-w-7xl px-4 py-4">
                {children}
            </main>
        </div>
    );
}

export default Layout;