import React, {useEffect} from 'react';
import Navbar from "./Navbar";
import Footer from "./Footer";
import Head from 'next/head';


const Layout = ({children}: {children: React.ReactNode}) => {

    useEffect(() => {
        const isDarkMode = sessionStorage.getItem("darkMode");
        if(!JSON.parse(isDarkMode!)) {
            sessionStorage.setItem("darkMode", JSON.stringify(false));
        }
    }, [])

    return ( 
        <div>
            <Head>
                <title>Real State</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/house_icon.png" />
            </Head>
            <Navbar />  
            <main className="container mx-auto max-w-7xl px-4 py-4">
                {children}
                <Footer />
            </main>
        </div>
    );
}

export default Layout;